name: Daily Bread Trigger

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call Daily Bread API
        run: |
          curl -X GET "https://daily-bread-omega.vercel.app/api/sendBread?secret=${{ secrets.SECRET_KEY }}"
